users branch initial commit
MUTABAZI-D/fitness-tracker-md pull request #2
Opened 2024-07-08 08:52 UTC by MUTABAZI-D

here is the initial commit for my users module so please review it , regards...

2024-07-17 20:11 UTC, kzngoga approved these changes
@MUTABAZI-D Pls check the below comments!

- When searching the pages also should reflect the search results 
![image](https://github.com/user-attachments/assets/a22d4416-3bc8-49c6-863e-86b19cd93516)

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/UsersTable.jsx
> +  const filteredUsers = users.filter((user) =>
- I'm getting an error here:
Maybe before filtering the users, you can first check if the array is **not empty** or do like this **users?.filter**
![image](https://github.com/user-attachments/assets/b445eb60-c8f7-4ce5-b9e1-92992383e72f)

2024-07-17 20:11 UTC, kzngoga commented on src/store/usersFeature/usersThunk.js
> +const API_URL = import.meta.env.VITE_API_URL;
the **API_URL** should be something like this:
![image](https://github.com/user-attachments/assets/aabe2d92-7e6e-404b-9cc0-4e72e23c5db6)

So that we can append the same URL for different resources. (i.e. users, workflows)

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/AddUserButton.jsx
> +export const AddUserButton = ({
Rename this file to **AddUserModal** and move it to **/src/components/users**

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/AddUserButton.jsx
> +    toast.error('Operation cancelled!');
Pls remove this **toast** it's not really necessary!

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/DisplayUserTable.jsx
> +export const DisplayUserTable = ({ currentUsers, editUser, userToEdit }) => {
Move this file to **/src/components/users**

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/MenuButton.jsx
> +export const MenuButton = ({ userId, editUser, userToEdit }) => {
Move this file to **/src/components/users** & rename to **UserActionMenu**

2024-07-17 20:11 UTC, kzngoga commented on src/components/common/UsersTable.jsx
> +export const UsersTable = ({ searchQuery }) => {
Move this file to **/src/components/users**

2024-07-17 20:11 UTC, kzngoga commented on src/components/layout/SearchAppBar.jsx
> +            SEARCH FOR USERS
Use Lowercase.

2024-07-17 20:12 UTC, kzngoga requested changes
@MUTABAZI-D check the changes above!

2024-07-23 08:29 UTC, MUTABAZI-D commented
made some changes as requested please kindly review it , regards ...

2024-08-05 09:07 UTC, kzngoga requested changes
@MUTABAZI-D Pls resolve this issue first of all, All others look good!

https://prnt.sc/0eqJnL5PmvxK

2024-08-05 09:59 UTC, MUTABAZI-D commented
made changes requested , so kindly review it please @kzngoga .

2024-08-05 10:02 UTC, kzngoga commented
> made changes requested , so kindly review it please @kzngoga .

There's another error! @MUTABAZI-D pls check carefully and remove all errors:
https://prnt.sc/TwW8vurJBG7j

2024-08-05 19:01 UTC, MUTABAZI-D commented
made sure there are no errors related to workouts feature again. @kzngoga  so please re-review it again teacher!!

2024-08-07 20:24 UTC, merged