added the Feat/workouts branch
MUTABAZI-D/fitness-tracker-md pull request #3
Opened 2024-08-19 10:10 UTC by MUTABAZI-D

added the last piece of the jigsaw which is the workouts feature , so @kzngoga  kindly review it please !!!

2024-08-22 21:06 UTC, kzngoga requested changes
@MUTABAZI-D 

- I couldn't run the app due to this error. https://prnt.sc/rDEeDtLObuzw I think the issue is that you didn't add the **workoutsReducer** in the store file

I'll review more once this issue is fixed.

2024-08-23 08:56 UTC, MUTABAZI-D commented
yes master!!! now i think the workouts branch is ready and sorry for the inconvenience @kzngoga . so please review

2024-08-27 12:45 UTC, kzngoga requested changes
@MUTABAZI-D Pls check & fix these feedback issues:

- In the table you need to fix these issues https://prnt.sc/8iAYmLCrAUBG:
	- You need to show the user information instead of the user id only. (name & phone)
	- You also need to format the date (Show the date in this format ex: 27/06/2024)
	- The search should work on both **name** and **type** fields.
	- Pls show a text like **No workouts found!** when there are no workouts found or the search results returned no data. not like this: https://prnt.sc/S5GZHw4S9TAl
	- Also the **table results** need to be sortable for now sort by date in descending order. (meaning today's date should be displayed first)
- You also need to change the hover background for this **button** https://prnt.sc/LoCqzomNErYy the current background isn't visible. you can only reduce the opacity of the button to **0.8** when it's hovered on.
- Pls remove this field (https://prnt.sc/B5whmJ-stB8O) just send today's date when adding the workout. also remove it in the edit form
- Before deleting a **workout** show a modal for confirming the action, it should have 2 buttons. i.e: **proceed** & **cancel**
	- When **cancel** is clicked then close the modal
	- When **Proceed** is clicked the delete the record

2024-08-27 12:45 UTC, kzngoga commented on src/components/layout/WorkoutsHeader.jsx
> +        WORKOUTS
Use a lowercase text here. and style it to **uppercase**.

2024-08-27 12:45 UTC, kzngoga commented on src/components/workouts/AddWorkoutModal.jsx
> +                    value: 1,
Change the **min value** to 10 minutes

2024-08-27 12:45 UTC, kzngoga commented on src/components/workouts/AddWorkoutModal.jsx
> +                    message: 'Calories burned must be at least 1 Kcal',
Change the **min value** to 50Kcal

2024-08-27 12:45 UTC, kzngoga commented on src/components/workouts/AddWorkoutModal.jsx
> +              <LocalizationProvider dateAdapter={AdapterDayjs}>
Pls remove the **date field** you need to just pass the **today's date**.

2024-08-27 12:45 UTC, kzngoga commented on src/components/workouts/WorkoutsTable.jsx
> +          WORKOUTS
Use lowercase text!

2024-09-04 08:13 UTC, MUTABAZI-D commented
hey master!! , i just added other info from user such as phone and name , but also corrected other requested changes . so kindly re-review it please @kzngoga

2024-09-11 07:34 UTC, kzngoga requested changes
@MUTABAZI-D some few things to change, before we can merge:

- Remove the UserID in the table (https://prnt.sc/07m4MREynIi5)
- This one wasn't updated:
	- You also need to change the hover background for this button [prnt.sc/LoCqzomNErYy](https://prnt.sc/LoCqzomNErYy) the current background isn't visible. you can only reduce the opacity of the button to 0.8 when it's hovered on.

2024-09-11 17:28 UTC, MUTABAZI-D commented
made requested changes master @kzngoga . please review and merge.

2024-09-12 07:40 UTC, merged