Feat/user details
MUTABAZI-D/fitness-tracker-md pull request #4
Opened 2024-09-26 06:01 UTC by MUTABAZI-D

Hey Boss @kzngoga i have  just just worked user details page , please review it and make necessary comments

2024-10-04 21:38 UTC, kzngoga requested changes
@MUTABAZI-D I didn't review much, but just encountered some unclear implementations & bugs!

- Pls, why did you add the **redux-persist** package?
- Also I keep getting this error when accessing the **users page** https://prnt.sc/YpFcJF2KKPos, not sure why!
- Another thing, is that I deleted all the records in **db.json** but I can still see these workouts: https://prnt.sc/wi56FBMqIJyz
- I think the **redux-persist** package is not needed in any of the usecases in this exercise

2024-10-14 11:13 UTC, kzngoga requested changes
@MUTABAZI-D looks good, but I need you to work on some changes!

- This page needs to have a sidebar and navbar as the other pages. Pls also add a back button at the top to redirect to the **users page**
https://prnt.sc/5HkNaqoGrVy7

- Remove the **follow** & **message** buttons

2024-10-14 11:13 UTC, kzngoga commented on package.json
> +    "redux-persist": "^6.0.0"
Remove this package from **package.json**

2024-10-14 11:13 UTC, kzngoga commented on src/components/users/UserActionMenu.jsx
> +const options = ['Edit', 'Delete', 'Details'];
Change the menu item to **view details**

2024-10-14 11:13 UTC, kzngoga commented on src/pages/UserDetailsPage.jsx
> +                {[
Declare this array outside the return function

2024-10-15 10:16 UTC, MUTABAZI-D commented
hey boss @kzngoga , worked really carefully on requested changes !!! please review .

2024-10-31 08:00 UTC, kzngoga approved these changes
Looks good, now we can merge!

2024-10-31 08:01 UTC, merged